name: meson CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install check manually
      run: sudo apt-get install check
    - name: Install valgrind manually
      run: sudo apt-get install valgrind
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - uses: BSFishy/meson-build@v1.0.3
      with:
        action: test
        directory: build
        setup-options: -Db_coverage=true -Dtest-settings=true
        options: --verbose --wrap=valgrind
        meson-version: 0.53.2
        ninja-version: 1.9.0.post1
        gcovr-version: 4.2
