name: meson CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Install check manually
      run: sudo apt-get install check
    - uses: actions/checkout@v2
    - name: Install meson
      run: python -m pip install meson==0.53.2
    - name: Install ninja
      run: python -m pip install ninja==1.9.0.post1
    - name: Setup meson
      run: meson -Dtest-settings=true . build_lib
    - name: Compile and run tests
      run: ninja -C build_lib test
    #- uses: actions/setup-python@v1
    #- uses: BSFishy/meson-build@v1.0.3
    #  with:
    #    action: test
    #    directory: build
    #    setup-options: -Db_coverage=true -Dtest-settings=true
    #    options: --verbose
    #    meson-version: 0.53.2
    #    ninja-version: 1.9.0.post1
    #    gcovr-version: 4.2

  run_valgrind:
    if: ${{ success() }}
    needs: build_tests
    runs-on: ubuntu-latest
    steps:
    - name: Install valgrind manually
      run: sudo apt-get install valgrind
    - name: Run valgrind on unittest_common
      run: valgrind $GITHUB_WORKSPACE/build_lib/tests/check/unittest_common
      shell: bash
